services:
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd
      # ✅ Escucha en todas las interfaces (dentro del contenedor)
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # ✅ Anuncia URLs alcanzables dentro de la red de Docker
      - ETCD_ADVERTISE_CLIENT_URLS=http://milvus-etcd:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://milvus-etcd:2380
      # Mantenimiento recomendado
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./volumes/etcd:/etcd
    networks: [milvus-net]
    restart: unless-stopped

  milvus-minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    container_name: milvus-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/minio_data"]
    volumes:
      - ./volumes/minio:/minio_data
    networks: [milvus-net]
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:v2.3.16
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]  # 👈 clave para que arranque Milvus
    environment:
      - ETCD_ENDPOINTS=milvus-etcd:2379
      - MINIO_ADDRESS=milvus-minio:9000
    ports:
      - "19530:19530"  # gRPC
      - "9091:9091"    # HTTP (métricas/diagnóstico)
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    depends_on:
      - milvus-etcd
      - milvus-minio
    networks: [milvus-net]
    restart: unless-stopped

networks:
  milvus-net: {}
